HedvigInsurance/web

package.json
src/App.js
src/components/Footer/__snapshots__/footer.test.js.snap
src/components/Footer/footer.css
src/components/Footer/index.js
src/components/Header/header.css
src/components/Header/index.js
src/components/styles/button.css
src/features/landing/index.js
src/features/landing/sections/CallToAction/index.js
src/features/landing/sections/Splash/index.js
src/features/static/AboutUs/__snapshots__/aboutus.test.js.snap
src/features/static/AboutUs/index.js
src/features/static/Contact/__snapshots__/contact.test.js.snap
src/features/static/Contact/index.js
src/features/static/Download/index.js
src/features/static/FAQ/index.js
src/features/static/Legal/__snapshots__/legal.test.js.snap
src/features/static/Legal/index.js
src/features/static/Terms/index.js
src/features/static/common.js
src/reducers/landing.js
src/reducers/peril.js
src/services/Navigation.js
yarn.lock

Reverts HedvigInsurance/web#1
Cleaning up mess caused by https://github.com/HedvigInsurance/web/pull/2

Revert "Add a mobile header nav"

---

src/components/Footer/__snapshots__/footer.test.js.snap
src/components/Footer/footer.css
src/components/Footer/index.js

Removing duplicate app download links from footer

---

src/pages/sections/Splash/index.js
src/pages/sections/Splash/splash.css

Testing new hero header heading and subheading

---

src/pages/faq/__snapshots__/faq.test.js.snap
src/pages/faq/index.js

FAQ: Link to new policy

---

src/components/AppLink/index.js
src/pages/download/index.js

Start tracking when you click app links and when sending sms.

Track app link click/sms

---

src/components/AppLink/index.js

- We take the tags array, join it with commas and dump it
into the label field

Track tags in segment

---

src/cms/preview-templates/landing-page-preview.js
static/admin/config.yml

- accidentally removed student page 🙈 
- fix fetching data for pricing section

Fix cms issues

---

src/components/Footer/index.js
static/assets/flags/en.svg
static/assets/flags/se.svg

Found some nice assets that IMO looks a bit better:

Make flags a bit nicer

---

src/templates/landing-page.js

Marketing did some strucutural changes which
made the site not build anymore. Now it does!

Fix site not building anymore

---

README.md

Update readme with info about dev setup

---

src/sections/about-us/hedvigers/desktop/__snapshots__/index.test.tsx.snap
src/sections/about-us/hedvigers/mobile/__snapshots__/index.test.tsx.snap

@Iamsamwhoami is this expected? It's on master at least but the builds were failing b/c snapshots weren't updated

Update snapshots in master

---

gatsby-browser.js
package.json

To improve browser support, tested and enables at least i.e. IE 11 (<- pun intended) and safari 9.

Add babel polyfill

---

.travis.yml
src/utils/blog-posts.ts
tsconfig.json

Make tsc stricter and actually perform typecheck in travis so it 💥 on failure

[solid system] tsc improvements

---

src/pages/student/index.en.md
static/admin/config.yml

[bug] Re-add cta text for /en/student

---

src/components/Breadcrumbs.tsx
src/templates/blog-post.js
src/templates/tag-page.js

[blog] Add breadcrumbs

---

src/html.js

Is this the best place?
@HedvigInsurance/clients

add snap pixel

---

gatsby-browser.js
package.json
src/cms/css-injector.tsx
src/components/Blog/BlogPost.tsx
yarn.lock

hopefully.
to be honest this is just so incredibly dumb

Fix our polyfill issues with IE11

---

netlify.toml
src/components/AppLink/index.js

Yes. 🖥
We are ready.
Next step is to point it towards the production environment. But lets use staging for now to see so the reverse proxy works as expected.

Web onboarding shallow release (staging) 🚀

---

netlify.toml

Don't merge until we're ready.

Web onboarding production 🚀

---

src/data/footer.yml
src/sections/about-us/press/index.tsx
src/sections/about-us/press/press-item.tsx

If we click a press link we should scroll to the press section on the about page 👋

Scroll to press section

---

src/pages/hemforsakring.md
src/pages/index.en.md
src/pages/index.md
src/pages/qasa.md
src/pages/student/index.en.md
src/pages/student/index.md
src/sections/landing/get-started.tsx
src/templates/landing-page.js
src/templates/student-page.js

Unkill web onboarding 🧟‍♀️
